---
trigger:
  branches:
    include:
      - master
      - develop
  paths:
    exclude:
      - README.md
      - CHANGELOG.md
      - CONTRIBUTING.md

pool:
  vmImage: 'windows-2022'

variables:
  buildConfiguration: 'Release'
  major: 6
  minor: 0
  # creates a counter called versioncounter and seeds it at 100 and then assigns the value to a variable named buildNo.
  buildNo: $[counter('versioncounter', 100)]

name: $(BuildDefinitionName)_$(SourceBranchName)_$(major).$(minor).$(buildNo)

steps:
# Windows script setting up  $(packageversion) of the nuget package based on branch
# Master branch
  - script: |
      echo ##vso[task.setvariable variable=packageversion]$(major).$(minor).$(buildNo)
    displayName: Setting Nuget PackageVersion
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
# Any other branch
  - script: |
      echo ##vso[task.setvariable variable=packageversion]$(major).$(minor).$(buildNo)-$(Build.SourceBranchName)
    displayName: Setting Prerelease Nuget PackageVersion
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')

  - script: |
      echo ##vso[task.setvariable variable=fileversion]$(major).$(minor).$(buildNo).0
    displayName: Setting FileVersion
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  - script: |
      echo ##vso[task.setvariable variable=fileversion]$(major).$(minor).0.$(buildNo)
    displayName: Setting Prerelease FileVersion
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')

  - task: NuGetToolInstaller@0
    displayName: Use Nuget
    inputs:
      versionSpec: ">6.8.0"

  - task: VersionDotNetCoreAssemblies@2
    displayName: Versioning netcore projects $(fileversion)
    inputs:
      Path: $(Build.SourcesDirectory)
      VersionNumber: $(fileversion)
      VersionRegex: \d+\.\d+\.\d+\.\d+
      FilenamePattern: .csproj
      Field: FileVersion
      OutputVersion: OutputedVersion

  - script: dotnet pack Xbim.MvdXml/Xbim.MvdXml.csproj -c Release -o $(Build.BinariesDirectory) /p:PackageVersion=$(packageversion)
    displayName: Xbim.MvdXml - packing

  - task: CopyFiles@2
    displayName: Copy to artifacts
    inputs:
      sourceFolder: $(Build.BinariesDirectory)
      contents: "**\\*.nupkg"
      targetFolder: $(build.artifactstagingdirectory)
      cleanTargetFolder: true

  - task: NuGetCommand@2
    displayName: Publish to MyGet Master
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: MyGetMaster
      versioningScheme: byEnvVar
      versionEnvVar: packageversion

  - task: NuGetCommand@2
    displayName: Publish to MyGet Develop
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: MyGetDev
      versioningScheme: byEnvVar
      versionEnvVar: packageversion

  - task: NuGetCommand@2
    displayName: Plugin - NuGet restore solution
    inputs:
      restoreSolution: "*.sln"
      feedsToUse: config
      nugetConfigPath: nuget.config

  - task: VSBuild@1
    displayName: Plugin - Build solution
    inputs:
      solution: "*.sln"
      msbuildArgs: /t:build
      platform: Any CPU
      configuration: $(BuildConfiguration)

  - task: NuGetCommand@2
    displayName: Plugin - NuGet pack
    inputs:
      command: pack
      packagesToPack: XbimPlugin.MvdXML.plugin.nuspec
      configuration: $(BuildConfiguration)
      versioningScheme: byEnvVar
      versionEnvVar: packageversion

# nuget restore sln
  - task: NuGetCommand@2
    displayName: Plugin - NuGet publish
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: MyGetPlugins
      packagesToPush: $(Build.ArtifactStagingDirectory)/**/XbimPlugin.*.nupkg
      versioningScheme: byEnvVar
      versionEnvVar: version

  - task: PublishBuildArtifacts@1
    displayName: Publish artifacts