//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace Xbim.MvdXml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://buildingsmart-tech.org/mvd/XML/1.1", IsNullable=false)]
    public partial class mvdXML {
        
        private ConceptTemplate[] templatesField;
        
        private ModelView[] viewsField;
        
        private string uuidField;
        
        private string nameField;
        
        private string codeField;
        
        private string versionField;
        
        private ConceptTemplateStatus statusField;
        
        private bool statusFieldSpecified;
        
        private string authorField;
        
        private string ownerField;
        
        private string copyrightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ConceptTemplate[] Templates {
            get {
                return this.templatesField;
            }
            set {
                this.templatesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ModelView[] Views {
            get {
                return this.viewsField;
            }
            set {
                this.viewsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ConceptTemplateStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                statusFieldSpecified = true;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string copyright {
            get {
                return this.copyrightField;
            }
            set {
                this.copyrightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://buildingsmart-tech.org/mvd/XML/1.1", IsNullable=false)]
    public partial class ConceptTemplate {
        
        private DefinitionsDefinition[] definitionsField;
        
        private AttributeRule[] rulesField;
        
        private ConceptTemplate[] subTemplatesField;
        
        private string uuidField;
        
        private string nameField;
        
        private string codeField;
        
        private string versionField;
        
        private ConceptTemplateStatus statusField;
        
        private bool statusFieldSpecified;
        
        private string authorField;
        
        private string ownerField;
        
        private string copyrightField;
        
        private string[] applicableSchemaField;
        
        private string[] applicableEntityField;
        
        private bool isPartialField;
        
        public ConceptTemplate() {
            this.isPartialField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Definition", IsNullable=false)]
        public DefinitionsDefinition[] Definitions {
            get {
                return this.definitionsField;
            }
            set {
                this.definitionsField = value;
            }
        }
        
        /// <remarks/>
        public AttributeRule[] Rules {
            get {
                return this.rulesField;
            }
            set {
                this.rulesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ConceptTemplate[] SubTemplates {
            get {
                return this.subTemplatesField;
            }
            set {
                this.subTemplatesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ConceptTemplateStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.statusFieldSpecified = true;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string copyright {
            get {
                return this.copyrightField;
            }
            set {
                this.copyrightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string[] applicableSchema {
            get {
                return this.applicableSchemaField;
            }
            set {
                this.applicableSchemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string[] applicableEntity {
            get {
                return this.applicableEntityField;
            }
            set {
                this.applicableEntityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool isPartial {
            get {
                return this.isPartialField;
            }
            set {
                this.isPartialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    public partial class DefinitionsDefinition {
        
        private DefinitionsDefinitionBody bodyField;
        
        private DefinitionsDefinitionLink[] linkField;
        
        /// <remarks/>
        public DefinitionsDefinitionBody Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Link", IsNullable=true)]
        public DefinitionsDefinitionLink[] Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    public partial class DefinitionsDefinitionBody {
        
        private string langField;
        
        private string[] tagsField;
        
        private string valueField;
        
        public DefinitionsDefinitionBody() {
            this.langField = "en";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        [System.ComponentModel.DefaultValueAttribute("en")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string[] tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    public partial class GenericReference {
        
        private string refField;
        
        private string hrefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://buildingsmart-tech.org/mvd/XML/1.1", IsNullable=true)]
    public partial class AttributeRule {
        
        private AttributeRuleEntityRules entityRulesField;
        
        private AttributeRuleConstraints constraintsField;
        
        private string attributeNameField;
        
        private string ruleIDField;
        
        private string descriptionField;
        
        /// <remarks/>
        public AttributeRuleEntityRules EntityRules {
            get {
                return this.entityRulesField;
            }
            set {
                this.entityRulesField = value;
            }
        }
        
        /// <remarks/>
        public AttributeRuleConstraints Constraints {
            get {
                return this.constraintsField;
            }
            set {
                this.constraintsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttributeName {
            get {
                return this.attributeNameField;
            }
            set {
                this.attributeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string RuleID {
            get {
                return this.ruleIDField;
            }
            set {
                this.ruleIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    public partial class AttributeRuleEntityRules {
        
        private EntityRule[] entityRuleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EntityRule")]
        public EntityRule[] EntityRule {
            get {
                return this.entityRuleField;
            }
            set {
                this.entityRuleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://buildingsmart-tech.org/mvd/XML/1.1", IsNullable=false)]
    public partial class EntityRule {
        
        private EntityRuleReferences referencesField;
        
        private EntityRuleAttributeRules attributeRulesField;
        
        private EntityRuleConstraints constraintsField;
        
        private string entityNameField;
        
        private string ruleIDField;
        
        private string descriptionField;
        
        /// <remarks/>
        public EntityRuleReferences References {
            get {
                return this.referencesField;
            }
            set {
                this.referencesField = value;
            }
        }
        
        /// <remarks/>
        public EntityRuleAttributeRules AttributeRules {
            get {
                return this.attributeRulesField;
            }
            set {
                this.attributeRulesField = value;
            }
        }
        
        /// <remarks/>
        public EntityRuleConstraints Constraints {
            get {
                return this.constraintsField;
            }
            set {
                this.constraintsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EntityName {
            get {
                return this.entityNameField;
            }
            set {
                this.entityNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string RuleID {
            get {
                return this.ruleIDField;
            }
            set {
                this.ruleIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    public partial class EntityRuleReferences {
        
        private GenericReference templateField;
        
        private string idPrefixField;
        
        /// <remarks/>
        public GenericReference Template {
            get {
                return this.templateField;
            }
            set {
                this.templateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string IdPrefix {
            get {
                return this.idPrefixField;
            }
            set {
                this.idPrefixField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    public partial class EntityRuleAttributeRules {
        
        private AttributeRule[] attributeRuleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttributeRule", IsNullable=true)]
        public AttributeRule[] AttributeRule {
            get {
                return this.attributeRuleField;
            }
            set {
                this.attributeRuleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    public partial class EntityRuleConstraints {
        
        private EntityRuleConstraintsConstraint[] constraintField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Constraint")]
        public EntityRuleConstraintsConstraint[] Constraint {
            get {
                return this.constraintField;
            }
            set {
                this.constraintField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    public partial class EntityRuleConstraintsConstraint {
        
        private string expressionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Expression {
            get {
                return this.expressionField;
            }
            set {
                this.expressionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    public partial class AttributeRuleConstraints {
        
        private AttributeRuleConstraintsConstraint[] constraintField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Constraint")]
        public AttributeRuleConstraintsConstraint[] Constraint {
            get {
                return this.constraintField;
            }
            set {
                this.constraintField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    public partial class AttributeRuleConstraintsConstraint {
        
        private string expressionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Expression {
            get {
                return this.expressionField;
            }
            set {
                this.expressionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://buildingsmart-tech.org/mvd/XML/1.1", IsNullable=false)]
    public partial class Concept {
        
        private DefinitionsDefinition[] definitionsField;
        
        private GenericReference templateField;
        
        private RequirementsRequirement[] requirementsField;
        
        private TemplateRules templateRulesField;
        
        private string uuidField;
        
        private string nameField;
        
        private string codeField;
        
        private string versionField;
        
        private ConceptTemplateStatus statusField;
        
        private bool statusFieldSpecified;
        
        private string authorField;
        
        private string ownerField;
        
        private string copyrightField;
        
        private string baseConceptField;
        
        private bool overrideField;
        
        public Concept() {
            this.overrideField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Definition", IsNullable=false)]
        public DefinitionsDefinition[] Definitions {
            get {
                return this.definitionsField;
            }
            set {
                this.definitionsField = value;
            }
        }
        
        /// <remarks/>
        public GenericReference Template {
            get {
                return this.templateField;
            }
            set {
                this.templateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Requirement", IsNullable=false)]
        public RequirementsRequirement[] Requirements {
            get {
                return this.requirementsField;
            }
            set {
                this.requirementsField = value;
            }
        }
        
        /// <remarks/>
        public TemplateRules TemplateRules {
            get {
                return this.templateRulesField;
            }
            set {
                this.templateRulesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ConceptTemplateStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.statusFieldSpecified = true;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string copyright {
            get {
                return this.copyrightField;
            }
            set {
                this.copyrightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string baseConcept {
            get {
                return this.baseConceptField;
            }
            set {
                this.baseConceptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool @override {
            get {
                return this.overrideField;
            }
            set {
                this.overrideField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    public partial class RequirementsRequirement {
        
        private string exchangeRequirementField;
        
        private RequirementsRequirementRequirement requirementField;
        
        private applicability applicabilityField;
        
        private bool applicabilityFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string exchangeRequirement {
            get {
                return this.exchangeRequirementField;
            }
            set {
                this.exchangeRequirementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RequirementsRequirementRequirement requirement {
            get {
                return this.requirementField;
            }
            set {
                this.requirementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public applicability applicability {
            get {
                return this.applicabilityField;
            }
            set {
                this.applicabilityField = value;
                this.applicabilityFieldSpecified = true;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool applicabilitySpecified {
            get {
                return this.applicabilityFieldSpecified;
            }
            set {
                this.applicabilityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    public enum RequirementsRequirementRequirement {
        
        /// <remarks/>
        mandatory,
        
        /// <remarks/>
        recommended,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("not-relevant")]
        notrelevant,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("not-recommended")]
        notrecommended,
        
        /// <remarks/>
        excluded,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    public enum applicability {
        
        /// <remarks/>
        export,
        
        /// <remarks/>
        import,
        
        /// <remarks/>
        both,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://buildingsmart-tech.org/mvd/XML/1.1", IsNullable=false)]
    public partial class TemplateRules {
        
        private object[] itemsField;
        
        private TemplateRulesOperator operatorField;
        
        private bool operatorFieldSpecified;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TemplateRule", typeof(TemplateRulesTemplateRule))]
        [System.Xml.Serialization.XmlElementAttribute("TemplateRules", typeof(TemplateRules))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("operator")]
        public TemplateRulesOperator @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.operatorSpecified = true;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    public partial class TemplateRulesTemplateRule {
        
        private string parametersField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    public enum TemplateRulesOperator {
        
        /// <remarks/>
        and,
        
        /// <remarks/>
        or,
        
        /// <remarks/>
        not,
        
        /// <remarks/>
        nand,
        
        /// <remarks/>
        nor,
        
        /// <remarks/>
        xor,
        
        /// <remarks/>
        nxor,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    public enum ConceptTemplateStatus {
        
        /// <remarks/>
        sample,
        
        /// <remarks/>
        proposal,
        
        /// <remarks/>
        draft,
        
        /// <remarks/>
        candidate,
        
        /// <remarks/>
        final,
        
        /// <remarks/>
        deprecated,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://buildingsmart-tech.org/mvd/XML/1.1", IsNullable=false)]
    public partial class ConceptRoot {
        
        private DefinitionsDefinition[] definitionsField;
        
        private ConceptRootApplicability applicabilityField;
        
        private Concept[] conceptsField;
        
        private string uuidField;
        
        private string nameField;
        
        private string codeField;
        
        private string versionField;
        
        private ConceptTemplateStatus statusField;
        
        private bool statusFieldSpecified;
        
        private string authorField;
        
        private string ownerField;
        
        private string copyrightField;
        
        private string applicableRootEntityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Definition", IsNullable=false)]
        public DefinitionsDefinition[] Definitions {
            get {
                return this.definitionsField;
            }
            set {
                this.definitionsField = value;
            }
        }
        
        /// <remarks/>
        public ConceptRootApplicability Applicability {
            get {
                return this.applicabilityField;
            }
            set {
                this.applicabilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Concept[] Concepts {
            get {
                return this.conceptsField;
            }
            set {
                this.conceptsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ConceptTemplateStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.statusFieldSpecified = true;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string copyright {
            get {
                return this.copyrightField;
            }
            set {
                this.copyrightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string applicableRootEntity {
            get {
                return this.applicableRootEntityField;
            }
            set {
                this.applicableRootEntityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    public partial class ConceptRootApplicability {
        
        private DefinitionsDefinition[] definitionsField;
        
        private GenericReference templateField;
        
        private TemplateRules templateRulesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Definition", IsNullable=false)]
        public DefinitionsDefinition[] Definitions {
            get {
                return this.definitionsField;
            }
            set {
                this.definitionsField = value;
            }
        }
        
        /// <remarks/>
        public GenericReference Template {
            get {
                return this.templateField;
            }
            set {
                this.templateField = value;
            }
        }
        
        /// <remarks/>
        public TemplateRules TemplateRules {
            get {
                return this.templateRulesField;
            }
            set {
                this.templateRulesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://buildingsmart-tech.org/mvd/XML/1.1", IsNullable=false)]
    public partial class ModelView {
        
        private DefinitionsDefinition[] definitionsField;
        
        private GenericReference baseViewField;
        
        private ModelViewExchangeRequirement[] exchangeRequirementsField;
        
        private ConceptRoot[] rootsField;
        
        private string uuidField;
        
        private string nameField;
        
        private string codeField;
        
        private string versionField;
        
        private ConceptTemplateStatus statusField;
        
        private bool statusFieldSpecified;
        
        private string authorField;
        
        private string ownerField;
        
        private string copyrightField;
        
        private string applicableSchemaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Definition", IsNullable=false)]
        public DefinitionsDefinition[] Definitions {
            get {
                return this.definitionsField;
            }
            set {
                this.definitionsField = value;
            }
        }
        
        /// <remarks/>
        public GenericReference BaseView {
            get {
                return this.baseViewField;
            }
            set {
                this.baseViewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ExchangeRequirement", IsNullable=false)]
        public ModelViewExchangeRequirement[] ExchangeRequirements {
            get {
                return this.exchangeRequirementsField;
            }
            set {
                this.exchangeRequirementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ConceptRoot[] Roots {
            get {
                return this.rootsField;
            }
            set {
                this.rootsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value?.ToLowerInvariant() ;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ConceptTemplateStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.statusFieldSpecified = true;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string copyright {
            get {
                return this.copyrightField;
            }
            set {
                this.copyrightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string applicableSchema {
            get {
                return this.applicableSchemaField;
            }
            set {
                this.applicableSchemaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    public partial class ModelViewExchangeRequirement {
        
        private DefinitionsDefinition[] definitionsField;
        
        private applicability applicabilityField;
        
        private bool applicabilityFieldSpecified;
        
        private string uuidField;
        
        private string nameField;
        
        private string codeField;
        
        private string versionField;
        
        private ConceptTemplateStatus statusField;
        
        private bool statusFieldSpecified;
        
        private string authorField;
        
        private string ownerField;
        
        private string copyrightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Definition", IsNullable=false)]
        public DefinitionsDefinition[] Definitions {
            get {
                return this.definitionsField;
            }
            set {
                this.definitionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public applicability applicability {
            get {
                return this.applicabilityField;
            }
            set {
                this.applicabilityField = value;
                this.applicabilityFieldSpecified = true;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool applicabilitySpecified {
            get {
                return this.applicabilityFieldSpecified;
            }
            set {
                this.applicabilityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ConceptTemplateStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.statusFieldSpecified = true;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string copyright {
            get {
                return this.copyrightField;
            }
            set {
                this.copyrightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    public partial class DefinitionsDefinitionLink {
        
        private string langField;
        
        private string titleField;
        
        private DefinitionsDefinitionLinkCategory categoryField;
        
        private bool categoryFieldSpecified;
        
        private string hrefField;
        
        public DefinitionsDefinitionLink() {
            this.langField = "en";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        [System.ComponentModel.DefaultValueAttribute("en")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DefinitionsDefinitionLinkCategory category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.categoryFieldSpecified = true;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categorySpecified {
            get {
                return this.categoryFieldSpecified;
            }
            set {
                this.categoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://buildingsmart-tech.org/mvd/XML/1.1")]
    public enum DefinitionsDefinitionLinkCategory {
        
        /// <remarks/>
        definition,
        
        /// <remarks/>
        agreement,
        
        /// <remarks/>
        diagram,
        
        /// <remarks/>
        instantiation,
        
        /// <remarks/>
        example,
    }
}
